org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.java.installations.paths=/opt/jdks/java-8,/opt/jdks/java-17,/usr/lib/jvm/java-21-openjdk-amd64,/opt/jdks/java-25
minecraft_version=1.20.1
loom_version=1.10.5
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
fabric_api_version=0.92.6+1.20.1
mod_version=1.0.0-r2
maven_group=cn.blockforge.generated
archives_base_name=mod_46937b35
